In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [26]:
data = pd.read_csv(r"housing_prices.csv")

In [27]:
norm_data = data.apply(lambda x: x / x.max(), axis=0)
norm_data

        size  bedrooms     price
0   0.469853       0.6  0.571367
1   0.357302       0.6  0.471353
2   0.535954       0.6  0.527218
3   0.316213       0.4  0.331476
4   0.669942       0.8  0.771396
5   0.443278       0.8  0.428490
6   0.342564       0.6  0.449921
7   0.318669       0.6  0.284325
8   0.308173       0.6  0.302900
9   0.333631       0.6  0.346478
10  0.433229       0.8  0.342905
11  0.446628       0.6  0.495785
12  0.422063       0.6  0.471494
13  1.000000       1.0  1.000000
14  0.283162       0.6  0.371339
15  0.513622       0.8  0.642806
16  0.294774       0.4  0.428490
17  0.276016       0.6  0.285612
18  0.582626       0.8  0.714385
19  0.676865       0.8  0.855837
20  0.394596       0.6  0.361337
21  0.421617       0.4  0.364338
22  0.358196       0.6  0.347050
23  0.438142       0.8  0.371339
24  0.868691       0.6  0.819974
25  0.245645       0.6  0.357051
26  0.325592       0.6  0.663666
27  0.564091       0.6  0.670096
28  0.491291       0.6  0.678668
29  0.588879       0.6  0.428490
30  0.410674       0.4  0.499929
31  0.223314       0.2  0.242749
32  0.455561       0.8  0.449921
33  0.700536       0.6  0.828547
34  0.404422       0.8  0.408487
35  0.320902       0.6  0.357051
36  0.276686       0.6  0.328475
37  0.476105       0.8  0.492928
38  0.941268       0.8  0.784398
39  0.482805       0.8  0.410059
40  0.371594       0.4  0.526504
41  0.499777       0.6  0.471353
42  0.573247       0.8  0.448636
43  0.267977       0.6  0.427204
44  0.190264       0.4  0.257037
45  0.413577       0.8  0.428490
46  0.268647       0.6  0.342192

In [28]:
training_set = norm_data.iloc[:41]

In [29]:
testing_set = norm_data.iloc[41:]

In [30]:
training_set.insert(0, 'X0', [1] * 41)
training_set

    X0      size  bedrooms     price
0    1  0.469853       0.6  0.571367
1    1  0.357302       0.6  0.471353
2    1  0.535954       0.6  0.527218
3    1  0.316213       0.4  0.331476
4    1  0.669942       0.8  0.771396
5    1  0.443278       0.8  0.428490
6    1  0.342564       0.6  0.449921
7    1  0.318669       0.6  0.284325
8    1  0.308173       0.6  0.302900
9    1  0.333631       0.6  0.346478
10   1  0.433229       0.8  0.342905
11   1  0.446628       0.6  0.495785
12   1  0.422063       0.6  0.471494
13   1  1.000000       1.0  1.000000
14   1  0.283162       0.6  0.371339
15   1  0.513622       0.8  0.642806
16   1  0.294774       0.4  0.428490
17   1  0.276016       0.6  0.285612
18   1  0.582626       0.8  0.714385
19   1  0.676865       0.8  0.855837
20   1  0.394596       0.6  0.361337
21   1  0.421617       0.4  0.364338
22   1  0.358196       0.6  0.347050
23   1  0.438142       0.8  0.371339
24   1  0.868691       0.6  0.819974
25   1  0.245645       0.6  0.357051
26   1  0.325592       0.6  0.663666
27   1  0.564091       0.6  0.670096
28   1  0.491291       0.6  0.678668
29   1  0.588879       0.6  0.428490
30   1  0.410674       0.4  0.499929
31   1  0.223314       0.2  0.242749
32   1  0.455561       0.8  0.449921
33   1  0.700536       0.6  0.828547
34   1  0.404422       0.8  0.408487
35   1  0.320902       0.6  0.357051
36   1  0.276686       0.6  0.328475
37   1  0.476105       0.8  0.492928
38   1  0.941268       0.8  0.784398
39   1  0.482805       0.8  0.410059
40   1  0.371594       0.4  0.526504

In [31]:
testing_set.insert(0, "X0", [1] * 6)

In [32]:
thetas = [0, 0, 0]

def hypothesis_function(thetas, i):
    res = 0
    for j in range(3):
        res += thetas[j] * training_set.iloc[i, j]
    return res

In [33]:
def derivative_calculation(j, thetas):
    res = 0
    for i in range(41):
        res += (hypothesis_function(thetas, i) - training_set.iloc[i, 3]) * training_set.iloc[i, j]
    return res

In [34]:
alpha = 0.001

In [35]:
thetas = [0, 0, 0]
def linreg():
    global thetas
    for _ in range(1000):
        temp_thetas = thetas[:]
        for j in range(3):
            temp_thetas[j] = temp_thetas[j] - alpha * derivative_calculation(j, thetas)
        thetas = temp_thetas[:]
    return thetas
print(linreg())

[0.1287861128274893, 0.5805277139455715, 0.16855056094138918]

In [36]:
def hypothesis_function_p(thetas, i):
    res = 0
    for j in range(3):
        res += thetas[j] * norm_data.iloc[i, j]
    return res
print(hypothesis_function_p(thetas, 42))

0.6138661905246782